FROM node:18-alpine

WORKDIR /frontend/spa

# add `/app/node_modules/.bin` to $PATH
ENV PATH /frontend/spa/node_modules/.bin:$PATH

# install dependencies
COPY spa/package.json .
COPY spa/package-lock.json .
RUN npm install --silent

COPY spa/src ./src
COPY spa/public ./public

# start app
CMD ["npm", "start"]